### ISSUE TITLE
The container stop itself

### ISSUE THREAD

**Issue by VMax4** [jordanpotter/docker-wireguard#1]
When i run it i have this error in the log file:

iptables v1.6.1: mark: bad mark value for option "--mark", or out of range.

Try `iptables -h' or 'iptables --help' for more information.

**Comment by jordanpotter** [comment]
Interesting, do you see any other errors in the Docker logs for that container?

**Comment by VMax4** [comment]
No, just that one

**Comment by jordanpotter** [comment]
That sounds very odd. From the `entrypoint.sh` file, the `wg-quick up $interface` line should have loads of log lines, and it happens before any of the `iptables` stuff.

Two questions:

1. What operating system are you using for your host? (Normally not a factor with Docker, but given we're using Wireguard on the host for performance, it's worth asking).
2. What does your config file look like? Are there any `iptables` operations in it?

**Comment by VMax4** [comment]
Hi, the host is a debian buster VPS server x86/64 and the config file is very simple without any iptables operations added, just the very standard one:

[Interface]
Address = 10.13.12.3/32
PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxx
ListenPort = 51820
DNS = 1.1.1.1

[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxx
Endpoint = xxxxxxxxxxxxxxxxxxxxxxxxxxx
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1


For the server, sudo hostnamectl returns:

Static hostname: xxxx
Icon name: computer-vm
Chassis: vm
Machine ID: xxxxxxxx
Boot ID: xxxxxxx
Virtualization: kvm
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 5.5.0-0.bpo.2-amd64
Architecture: x86-64

and sudo lsb_release -a returns:

No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster

**Comment by jordanpotter** [comment]
I'm using the exact same setup, but I'm running Debian Buster locally. My config looks the exact same too, except `Interface.DNS` is my VPN provider's DNS, and `Peer.AllowedIPs` is simply `0.0.0.0/0`.

I'd like to spin up a Debian VM locally via VirtualBox and double-check your findings. If there's a bug somewhere, I'd like to get this fixed quickly.

In the meantime, have you checked whether you can start wireguard on the host using that same config file?

**Comment by jordanpotter** [comment]
Hey @VMax4 , I created a Debian VM locally and tested the container by running:
```
$ docker run --name wireguard                                        \
    --cap-add=NET_ADMIN                                              \
    -v /path/to/conf/mullvadus2.conf:/etc/wireguard/mullvadus2.conf  \
    jordanpotter/wireguard
```
Followed by:
```
$ docker run -it --rm                                                \
    --net=container:wireguard                                        \
    appropriate/curl http://httpbin.org/ip
```

Everything works fine, so I'm thinking there's something different about your setup 🤔 

Out of curiosity, what's the name of the config file that you're using? Additionally, what's the command you're using to run the Docker container?

**Comment by jordanpotter** [comment]
Given no communication, I'm going to assume the issue has been resolved. Please re-open if that's not the case!

**Comment by shiouen** [comment]
Many years later, I experience the very same issue.

```sh
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add dev wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.30/24 dev wg0
[#] ip link set mtu 1370 up dev wg0
iptables v1.8.11 (nf_tables): mark: bad integer value for option "--mark", or out of range.

Try `iptables -h' or 'iptables --help' for more information.
```

I run this container as a sidecar container in a k3s pod. Since the wg0 interface is created successfully and the pod attempts to restart the container, any additional startup will result in:

```sh
wg-quick: `wg0' already exists
```

Initial error does not occur much, but when it does, it's quite the pickle. I am currently unable to pinpoint what conditions cause it to occur.

**Comment by shiouen** [comment]
**How I fixed the issues**

1) bootloops

Before wg-quick, we have to make sure wg0 does not exist.

```sh
ip link del wg0 2>/dev/null || true
```

2) mark

I can fix the mark issue by adding `FwMark = 51820` to `wg0.conf` in the `[Interface]` section.

debugging logs which helped me figure out the invalid value of mark:

```sh
/# wg show wg0 fwmark
Unable to access interface: No such device

/# ./entrypoint.sh 
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add dev wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.30/24 dev wg0
[#] ip link set mtu 1370 up dev wg0
iptables v1.8.11 (legacy): mark: bad integer value for option "--mark", or out of range.

Try `iptables -h' or 'iptables --help' for more information.
/# wg show wg0 fwmark
off
```

The fwmark for wg0 is 'off', definitely not an integer. As you can see above, I also tried with legacy iptables but that does not seem to make a difference.

I am unsure if this 'fix' has unwanted side effects.
