### ISSUE TITLE
Local dns server

### ISSUE THREAD

**Issue by Yrlish** [jordanpotter/docker-wireguard#13]
I would want to configure the wireguard container to be able to communicate to lan, to dns and a few local services. 

Can I exempt certain ips or local subnet to be blocked somehow?

**Comment by jordanpotter** [comment]
Hey @Yrlish, the kill switch forbids traffic that does not go over the Wireguard connection. This is part of the project's core design.

Given your use case, are you sure you want a kill switch for your Wireguard connection?

**Comment by jordanpotter** [comment]
Hey @Yrlish, the kill switch forbids traffic that does not go over the Wireguard connection. This is part of the project's core design.

With some work, it's likely possible to modify the `iptables` rules to allow for specific subnets. However I haven't experimented with this myself. If you implement a solution that does not jeopardize the kill switch, I would very much welcome a PR!

**Comment by Yrlish** [comment]
The main reason I use this container is for the kill switch feature, having other containers dependent on this losing the Internet connection. I just want these to be able to talk to some local network destinations for internal communication.

Unfortunately I don't have any experience with iptables or how that layer of network works in docker containers. So yeah, I value the kill switch so a solution should not jeopardize that of course.

**Comment by jordanpotter** [comment]
Just to clarify, do you want:
1. The Wireguard container to have access to local subnets
2. The container that connects to the Wireguard container to have access to local subnets

Btw, this feature might be similar in nature to what's requested in https://github.com/jordanpotter/docker-wireguard/issues/10.

**Comment by Yrlish** [comment]
Isn't first point the same as the second? The network in the wireguard container and the other container with `network_mode: service:wireguard` (docker-compose) has the same localhost, meaning they are the same. So if I want to communicate out to LAN in my other container, then the wireguard container needs to be able to communicate out to LAN.

The issue #10, is about an outside source wanting to communicate into the container. This I have already solved via a reverse proxy.

**Comment by Yrlish** [comment]
It seems I cannot add custom iptables rules because they are followed in order. I would need to remove the default reject rule to add custom ones and then re-add the default reject rule again.

This means the image need to be adjusted and I haven't dug into that part of Docker yet. 😛 

Add allow LAN rules with an environment variable maybe? 🤔

**Comment by jordanpotter** [comment]
Re Docker network: you are correct, they are the same. However when I'm implementing this feature, I want to make sure I'm testing with a setup that properly emulates your use case. The more specific, the better 👍 

For both this and https://github.com/jordanpotter/docker-wireguard/issues/10 (although the proxy solution certainly works and is what I use), I believe we'll need to modify the IP stack. Unfortunately I don't have Docker networking and `iptables` completely memorized (does anyone??), so this will take a bit of experimentation on my end.

However I _believe_ we need to do the following:
1. Add an optional environment variable for specifying the local subnet
1. Route traffic for the local subnet through `eth0` via `ip route add`
1. Modify `iptables` to _not_ reject traffic destined to the local subnet via `eth0`

Afterwards test that:
1. The Wireguard network can reach services on the local subnet
1. Traffic _not_ destined for the local subnet is rejected if Wireguard is down (i.e. the kill switch works)

However I need to dig deeper into how this will work with Docker's different networking configurations. In `bridge` mode traffic to the local subnet will route through the `docker0` bridge, which should meet your use case as long as the requisite ports are opened. But I need to verify.

**Comment by Yrlish** [comment]
What you are planning to do feels to me that's on the correct path.

My usecase:
**Container 1 - network mode: service:wireguard**
Container 1 wants to communicate with service.lan via HTTP, also needs to ask local dns server for directions.

**Container 2**
Container 2 runs http://service.lan

**Comment by jordanpotter** [comment]
Excellent, thanks for the details! And just to clarify, "local DNS server" is a server running on your local network. We're _not_ talking about the Docker embedded DNS server.

**Comment by Yrlish** [comment]
Yes, number 2. Not the docker embedded dns server. 😛

**Comment by Yrlish** [comment]
A DNS server running on the local network on another host. Not the embedded docker one.

**Comment by jordanpotter** [comment]
Perfect, that makes sense 👍

**Comment by jordanpotter** [comment]
Giving an update before heading to bed 😴 

Here's a change to `entrypoint.sh` that will allow outbound traffic to a local subnet while NOT impacting the kill switch. It goes directly before the `shutdown()` function.

```
if [[ "$LOCAL_SUBNET" ]]; then
    default_route_ip=$(ip route | grep default | awk '{print $3}')
    ip route add $LOCAL_SUBNET via $default_route_ip
    iptables -I OUTPUT -d $LOCAL_SUBNET -j ACCEPT
fi
```

I have also verified that this will allow traffic to a DNS server running on the local subnet, as long as the IP address of that DNS server is specified in the Wireguard config file.

**Comment by Yrlish** [comment]
Sorry for being absent.

This sounds great! 

Also, is your comment urging me to build my own imagine? Because I don't know how to do that. 😛

**Comment by jordanpotter** [comment]
Nope! I've just been busy this week and didn't want to block you if you wanted to get a head start on updating the image.

I hope to have time to add support for local subnets this weekend.

**Comment by Yrlish** [comment]
Ah I see! No worries! 🙂

**Comment by jordanpotter** [comment]
This feature has been added in version `2.1.0`. Instructions have also been added to the README 👍

**Comment by Yrlish** [comment]
I will check it out this weekend 🙂
