### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ecsuae** [jordanpotter/docker-wireguard#16]
i am trying to setup wireguard client in docker and trying your image, no mater what version i select i end up in  following error
docker run --name wireguard --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl "net.ipv4.conf.all.src_valid_mark=1" -v /usr/src/wg/config/wg0.conf:/etc/wireguard/wg0.conf  jordanpotter/wireguard:2.1.1
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.252.1.17/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] ip -4 route add 10.252.1.0/24 dev wg0
iptables v1.8.4 (legacy): mark: bad integer value for option "--mark", or out of range.

Try `iptables -h' or 'iptables --help' for more information

can you guide what is wrong, mm purpose is to access spilit tunnels accessable  from docker container to host machine.i can run linuxserver docker instructions and wireguard runs perfectly just cannot access the tunnel networks from host.

**Comment by jordanpotter** [comment]
Hey @ecsuae! How odd, your logs should look like:
```
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.252.1.17/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] echo skipping setting net.ipv4.conf.all.src_valid_mark
skipping setting net.ipv4.conf.all.src_valid_mark
[#] iptables-restore -n
Skipping ipv6 kill switch setup since ipv6 interface was not found
```

Strangely, you're missing the `[#] wg set wg0 fwmark 51820` line 🤔 

Could you give me more details?
1. What operating system are you using on the host?
2. What version of wireguard does the host have installed?
3. Are you using the `jordanpotter/wireguard` image from Docker Hub?

**Comment by ecsuae** [comment]
1-i am using ubuntu 20.04 LTS server on host.
2-Docker version 20.10.7, build f0df35
3-yes i am using the image from docker hub, i am running the command as is


docker run --name wireguard --cap-add NET_ADMIN --cap-add SYS_MODULE --sysctl "net.ipv4.conf.all.src_valid_mark=1" -v /usr/src/wg/config/wg0.conf:/etc/wireguard/wg0.conf jordanpotter/wireguard:2.1.1

**Comment by jordanpotter** [comment]
Hrmm, what does your (redacted) configuration file look like?

**Comment by ecsuae** [comment]
i changed the keys and ips for security reason
[Interface]
Address = 10.0.1.17/32
PrivateKey = iCdo+TVMewssdafredwkslsqLvbmFs21x+mC3Gw=
DNS = 1.1.1.1

[Peer]
PublicKey = sja+WoBbxHogBQ38R9sfsedwjsOYKMw21uXTkQ=
PresharedKey = EiikvfXUQlvisde3whsjl9QdAPt+t2xsZ/waLQ=
AllowedIPs = 10.252.1.0/24
Endpoint = 198.39.65.234:51820
PersistentKeepalive = 15

**Comment by jordanpotter** [comment]
It looks like your config file is incorrect. I tried modifying my own Wireguard config to match yours and got the same error. Does your config file work outside of Docker on your Ubuntu host? If not, I would get that working first.

If I understand your configuration correctly, you want traffic to `10.252.1.0/24` to be sent to your server at `198.39.65.234`. The Arch wiki has a good guide for this setup: https://wiki.archlinux.org/title/WireGuard#Usage

**Comment by ecsuae** [comment]
config file is correct and working fine in docker (linuxserver/wireguard) , I can access wireguard networks from inside container , my requirement is to use the wireguard networks from the host.I can make that work as well if I use network:host , but my problem is I have 3cx pbx working on host which stops working if wireguard is working.I need only host can communicate with wireguard network that is working in container.I tried to use your instructions but stuck with  ("--mark", or out of range.)

**Comment by jordanpotter** [comment]
I believe this is the line that is failing, which is used for the kill switch: https://github.com/jordanpotter/docker-wireguard/blob/777a5c044ee5929a8b1996a3bbf4a171d90e1bb1/entrypoint.sh#L30

I'm curious why `wg show wg0 fwmark` would fail with your configuration...

**Comment by jordanpotter** [comment]
To help debug, I added `wg show $interface` [here](https://github.com/jordanpotter/docker-wireguard/blob/777a5c044ee5929a8b1996a3bbf4a171d90e1bb1/entrypoint.sh#L27).

With a Wireguard config from Mullvad, I see:
```
interface: mullvad
  public key: <redacted>
  private key: (hidden)
  listening port: 37584
  fwmark: 0xca6c

peer: <redacted>
  endpoint: <redacted>
  allowed ips: 0.0.0.0/0
```

However if I change the config's `AllowedIPs` to something else, like `10.0.0.0/8`, I see:
```
interface: mullvad
  public key: <redacted>
  private key: (hidden)
  listening port: 37584

peer: <redacted>
  endpoint: <redacted>
  allowed ips: 10.0.0.0/8
```

`fwmark` is never set!

**Comment by jordanpotter** [comment]
@ecsuae try adding `Interface.FwMark` to your Wireguard config file and let me know if that solves your problem. Your new config file would look something like:
```
[Interface]
Address = 10.0.1.17/32
PrivateKey = iCdo+TVMewssdafredwkslsqLvbmFs21x+mC3Gw=
DNS = 1.1.1.1
FwMark = 51820

[Peer]
PublicKey = sja+WoBbxHogBQ38R9sfsedwjsOYKMw21uXTkQ=
PresharedKey = EiikvfXUQlvisde3whsjl9QdAPt+t2xsZ/waLQ=
AllowedIPs = 10.252.1.0/24
Endpoint = 198.39.65.234:51820
PersistentKeepalive = 15
```

**Comment by jordanpotter** [comment]
Thanks to [this article](https://casavant.org/2020/10/10/wireguard-fwmark.html), which explains that when `AllowedIPs` isn't `0.0.0.0/0` (which is the case for your configuration), Wireguard won't set `fwmark` because it doesn't need it.

Of course, this is problematic for this Docker image, since it uses `fwmark` for the kill switch.

**Comment by jordanpotter** [comment]
@ecsuae try adding `Interface.FwMark` to your Wireguard configuration file. So it'd look something like this:
```
[Interface]
Address = 10.0.1.17/32
PrivateKey = iCdo+TVMewssdafredwkslsqLvbmFs21x+mC3Gw=
DNS = 1.1.1.1
FwMark = 51820

[Peer]
PublicKey = sja+WoBbxHogBQ38R9sfsedwjsOYKMw21uXTkQ=
PresharedKey = EiikvfXUQlvisde3whsjl9QdAPt+t2xsZ/waLQ=
AllowedIPs = 10.252.1.0/24
Endpoint = 198.39.65.234:51820
PersistentKeepalive = 15
```

**Comment by jordanpotter** [comment]
Hey @ecsuae, going to close this out since it's been a few weeks of silence. However please reopen if I failed to resolve your issue! 👍
