### ISSUE TITLE
ARM64 build

### ISSUE THREAD

**Issue by Smart123s** [jordanpotter/docker-wireguard#17]
On my RPI4 `docker build .` ran without any issues, but it would be cool, if we could pull ARM64 images from the Docker Hub.

**Comment by jordanpotter** [comment]
Hey @Smart123s, great call! Did a bit of research, and looks like this is very possible with GitHub Actions. I'll try to find time this weekend to play around with this!

**Comment by jordanpotter** [comment]
Done! Starting with `jordanpotter/wireguard:2.1.2` images are built for amd64 AND arm64.

@Smart123s let me know how it works for you!

**Comment by Smart123s** [comment]
I pulled the `latest` tag (currently v2.1.2) and it works out of the box.

Thanks for creating this awesome project, it had helped me a lot.
