### ISSUE TITLE
Asymmetric routing / read only filesyste errors; leads to container stopping

### ISSUE THREAD

**Issue by kwkaiser** [jordanpotter/docker-wireguard#2]
**OS & Kernel:**
`Linux hostname 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Behavior:** 
Newly built docker image yields the following error _unless_ it is run in privileged mode:
`sysctl: setting key "net.ipv4.conf.all.src_valid_mark": Read-only file system`

This behavior persists even after changing the relevant values in /etc/sysctl.conf as described in the README and rebooting. This behavior only occurs for _newly_ generated images; running the jordanpotter/wireguard docker image obtained from the docker registry works fine with no errors under the same system.

**Command used to build image:**
`docker build -t jordanpotter/wireguard .`

Run in the docker-wireguard directory.

**Relevant wireguard conf:**
I tested this using a simple wireguard config from mullvad:

```

[Interface]
PrivateKey = xxxxxxxx
Address = xxxxxx
DNS = xxxxxx

[Peer]
PublicKey = xxxxx
AllowedIPs = xxxxxx
Endpoint = xxxxxx

```

**Comment by jordanpotter** [comment]
Hey @kwkaiser , thanks for the detailed description! My hypothesis is that there was a behavior change when the new version of Ubuntu was released, judging from the timing of these issues. However I hope to confirm that soon.

Most likely the fix will require just pinning the operating system of the base image.

**Comment by jordanpotter** [comment]
I've been able to confirm your same findings: the [hub.docker.com](https://hub.docker.com/r/jordanpotter/wireguard) image works fine, but building from scratch will fail with `sysctl: setting key "net.ipv4.conf.all.src_valid_mark": Read-only file system`. 

Unfortunately, this is true even after pinning the version of Ubuntu to 18.04. My suspicion is that a fix to Wireguard was backported, which now requires that sysctl key.

Still investigating though...

**Comment by jordanpotter** [comment]
So after investigating further, although the error `sysctl: setting key "net.ipv4.conf.all.src_valid_mark": Read-only file system` appears, the container continues to run fine. Additionally, containers that use the Wireguard container for networking work as well:

```
$ sudo docker run --rm --name wireguard --cap-add=NET_ADMIN -v /home/foo/mullvad-us7.conf:/etc/wireguard/mullvad-us7.conf wireguard-test
[#] ip link add mullvad-us7 type wireguard
[#] wg setconf mullvad-us7 /dev/fd/63
[#] ip -4 address add 10.64.18.89/32 dev mullvad-us7
[#] ip link set mtu 1420 up dev mullvad-us7
[#] resolvconf -a mullvad-us7 -m 0 -x
[#] wg set mullvad-us7 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev mullvad-us7 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
sysctl: setting key "net.ipv4.conf.all.src_valid_mark": Read-only file system
[#] iptables-restore -n
```

```
$ sudo docker run -it --rm appropriate/curl http://httpbin.org/ip
{
  "origin": "<my home ip>"
}

$ sudo docker run -it --rm --net=container:wireguard appropriate/curl http://httpbin.org/ip
{
  "origin": "<my vpn ip>"
}
```

**Comment by jordanpotter** [comment]
Continuing my testing, I ran an updated image on my personal server. Now, the `sysctl: setting key "net.ipv4.conf.all.src_valid_mark": Read-only file system` error stops the container. Only running in privileged mode works.

As an aside, I have discovered that Wireguard was shipped with Ubuntu 20.04 AND backported to 18.04. That would explain why using Ubuntu:18.04 or Ubuntu:20.04 as the base image exhibits the same behavior.

**Comment by jordanpotter** [comment]
I've updated the documentation to require `--privileged`. After some experimentation, it doesn't appear that any combination of Linux capabilities via `--cap-add` resolves the issue. Let me know if your research says otherwise.

I'm not a fan of running containers with `--privileged`, so I'd like to revisit this in the future. In the meantime, it appears that other developers are experiencing this same issue on the [Docker forums](https://forums.docker.com/t/sysctl-error-setting-key-net-ipv4-conf-all-src-valid-mark-read-only-file-system/92567/5).

**Comment by kwkaiser** [comment]
Awesome research, but unfortunately I have not found any potential solution outside of the `--privileged` flag either. I am also not keen on running containers as privileged. I tried playing around with alpine as a base image & installing / executing wireguard with its relevant repos to see if it would yield the same `sysctl: setting key "net.ipv4.conf.all.src_valid_mark": Read-only file system` errors. It did.

That would suggest that this is an upstream issue, yeah?

**Comment by jordanpotter** [comment]
Yeah, I believe you're right. I also tried adding `--sysctl="net.ipv4.conf.all.src_valid_mark=1"` to the `docker run` command, but that didn't seem to resolve the issue either:

```
docker run --name wireguard                                          \
    --cap-add=NET_ADMIN                                              \
    --sysctl="net.ipv4.conf.all.src_valid_mark=1"                    \
    -v /path/to/conf/mullvadus2.conf:/etc/wireguard/mullvadus2.conf  \
    jordanpotter/wireguard
```
