### ISSUE TITLE
Problems with ip6tables

### ISSUE THREAD

**Issue by kromsam** [jordanpotter/docker-wireguard#22]
I am encountering the issue that ip6tables is legacy. It is the same issue as here: https://github.com/qdm12/gluetun/issues/430

**Comment by rizzaro** [comment]
Try adding a volume like `-v /lib/modules:/lib/modules`.

**Comment by kzdixon** [comment]
I tried adding a volume as suggested and ran into this after:
```
modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko.zst): invalid module format
ip6tables-restore v1.8.7 (legacy): ip6tables-restore: unable to initialize table 'raw'
```

**Comment by Smart123s** [comment]
> I tried adding a volume as suggested and ran into this after:
> 
> ```
> modprobe: can't load module ip6_tables (kernel/net/ipv6/netfilter/ip6_tables.ko.zst): invalid module format
> ip6tables-restore v1.8.7 (legacy): ip6tables-restore: unable to initialize table 'raw'
> ```

I had the same issue, running `sudo insmod /lib/modules/5.18.6-zen1-1.1-zen/kernel/net/ipv6/netfilter/ip6_tables.ko.zst` fixed it. Replace `5.18.6-zen1-1.1-zen` with your kernel version.

Host: Arch Linux x64 (zen kernel)

**Comment by jordanpotter** [comment]
Hey everyone! Going to close this issue since it hasn't been updated in a while. Please comment and/or reopen if needed!
