### ISSUE TITLE
Please create docker images for other platforms.

### ISSUE THREAD

**Issue by schinckel** [jordanpotter/docker-wireguard#23]
Hi there,

I came across this while troubleshooting some Wireguard issues, and wanted to run it on my raspberry pi.

However there's no `linux/arm/v7` image available.

**Comment by jordanpotter** [comment]
Hey @schinckel, thanks for submitting this issue!

We currently have amd64 and arm64 (you can see them on the tags page [here](https://hub.docker.com/r/jordanpotter/wireguard/tags)). Adding arm/v7 should be straightforward. I'll take a look!

**Comment by jordanpotter** [comment]
Done! arm/v7 is now available starting in version 2.1.3 👍
