### ISSUE TITLE
Multi "LOCAL_SUBNET"

### ISSUE THREAD

**Issue by Paulpatou** [jordanpotter/docker-wireguard#24]
Hi,
Is it possible to add several "LOCAL_SUBNET" ?
If not, it would be interesting to have this feature.

**Comment by jordanpotter** [comment]
Hey @Paulpatou, it is currently _not_ possible to provide multiple values for `LOCAL_SUBNET`. However, this sounds like a great feature!

Should be easy to add by modifying [this logic](https://github.com/jordanpotter/docker-wireguard/blob/2.1.3/entrypoint.sh#L48-L52) to support a comma separated list of values (e.g. `LOCAL_SUBNET=10.1.0.0/16,10.2.0.0/16,10.3.0.0/16`). I should have time to update this in the coming weeks.

**Comment by seertenedos** [comment]
This would help me as well as i run both local network and a remote access wieguard to the box and i would like to access it from both but they are totally different subnets

**Comment by jordanpotter** [comment]
Hey @Paulpatou and @seertenedos, just created a PR to add this feature: https://github.com/jordanpotter/docker-wireguard/pull/27

If all looks good, I'll merge this in!

**Comment by seertenedos** [comment]
looks good to me.  I have not had a chance to test it sadly but i did look over the change

**Comment by jordanpotter** [comment]
Merged! This feature is available in version [2.1.4](https://hub.docker.com/layers/wireguard/jordanpotter/wireguard/2.1.4/images/sha256-c1ff8711433a4d7b883e83270474186af5a1f7135d5d63b93b7f518e8b7d771a)
