### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ericand1** [jordanpotter/docker-wireguard#26]
Hello, this docker container seems to be working well for me, thank for taking the time to create (and continually maintain) the repo!

I had a little trouble getting it to work because in Mullvad I needed to make sure that I only used IPv4 for the tunnel traffic option. Perhaps this was an issue with my environment, or obvious to most people, but the container would not start and had cryptic Permission Denied errors so it may be worth noting in the README.

Thanks again!

<img width="748" alt="image" src="https://user-images.githubusercontent.com/65682749/149055630-59bee4fd-2148-4093-bc64-86c472829934.png">

**Comment by jordanpotter** [comment]
Hey @ericand1, thanks for filing this issue and including a screenshot! I'm curious if this has something to do with your Docker environment, but regardless we should at least have a notice in the README 👍 

I'll double-check a few things in the coming weeks and update the README accordingly. Thanks again!

**Comment by rizzaro** [comment]
IPv6 works but you might have to use `--sysctl net.ipv6.conf.all.disable_ipv6=0`. Please give it a try and let us know.

**Comment by jordanpotter** [comment]
Hey everyone! Going to close this issue since it hasn't been updated in a while. Please comment and/or reopen if needed!
