### ISSUE TITLE
VPN Network Gateway

### ISSUE THREAD

**Issue by timeshadowrider** [jordanpotter/docker-wireguard#29]
Is there a way to use this as a local network gateway for all my devices on the network?

**Comment by BobWs** [comment]
+1

**Comment by jordanpotter** [comment]
Hrmm, have you tried starting a Docker container that's running a SOCKS proxy, then linking that container to your Wireguard container? That's a fairly common pattern for those that want to route traffic from a local machine through their Wireguard container.

**Comment by jordanpotter** [comment]
Hrmm, have you tried starting a Docker container that's running a SOCKS proxy, and linking that container to your Wireguard container? This won't route _all_ of your local network traffic, however might be the easiest solution if you just need to protect traffic for a few devices.

If you're looking for something more advanced, unfortunately that's beyond the scope of what I'm able to support with this Docker image.
