### ISSUE TITLE
Arm64 operation error

### ISSUE THREAD

**Issue by heku66** [jordanpotter/docker-wireguard#31]
Please take a look. I just use it as a client,
Armbian 23.05.0-trunk Bullseye with Linux 6.1.21-flippy-82+
The error log is as follows:

wireguard  | [#] ip -6 rule add table main suppress_prefixlength 0
wireguard  | [#] ip6tables-restore -n
wireguard  | modprobe: can't change directory to '/lib/modules': No such file or directory
wireguard  | ip6tables-restore v1.8.7 (legacy): ip6tables-restore: unable to initialize table 'raw'
wireguard  | 
wireguard  | Error occurred at line: 1
wireguard  | Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
wireguard  | [#] resolvconf -d mullvad -f
wireguard  | [#] ip -6 rule delete table 51820
wireguard  | [#] ip -6 rule delete table main suppress_prefixlength 0
wireguard  | [#] ip link delete dev mullvad
wireguard exited with code 2

**Comment by heku66** [comment]
Normal after adding the following parameters：
    volumes:
      - ./wg0.conf:/etc/wireguard/wg0.conf
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src

**Comment by jordanpotter** [comment]
Hey @heku66, thanks for the bug report! Are you intending to have IPv6 enabled? If so, I wonder if the fix discussed in https://github.com/jordanpotter/docker-wireguard/issues/26 works for you.

**Comment by jordanpotter** [comment]
Going to close this issue since it hasn't been updated in a while. Please comment and/or reopen if needed!
