### ISSUE TITLE
Experience with Synology

### ISSUE THREAD

**Issue by SuperMotzer** [jordanpotter/docker-wireguard#44]
Hello Jordan,
Do you have experience if your wireguard client is working on a synology NAS ? 
I'm still fighting with issue: 

[#] resolvconf -a wg0 -m 0 -x
could not detect a useable init system

Thank you,
Cheers,
Stephane

**Comment by jordanpotter** [comment]
Hey @SuperMotzer, unfortunately I don't have access to a Synology NAS so I can't test or debug this. But if you figure it out, please let me know so I can update the README!

**Comment by jordanpotter** [comment]
Hey @SuperMotzer, since it's been 3 months, I'm going to go ahead and close this. Please reopen if I can provide any assistance!
